version: '3'
services:
#=============================================================================
  jupyter-tutorial:
    build: ./dfile/note/
    container_name: m4.jupyter
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./note/:/home/jovyan/work/
      - ./.aws:/home/jovyan/.aws/
    command: start-notebook.sh --NotebookApp.token=''
#=============================================================================
  db1:
    image: mariadb
    container_name: cc104.rds.local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hahaha
    volumes:
      - ./data_mariadb/:/var/lib/mysql
#=============================================================================
  db2:
    image: mysql
    container_name: cc104.mysql.local
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hahaha
    volumes:
      - ./data_mysql/:/var/lib/mysql
#=============================================================================
  dynamodb:
    build: ./dfile/dynamo/
    container_name: cc104.dynamodb.local
    volumes:
      - ./data_dynamo:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath ./data
#=============================================================================

