FROM jupyter/base-notebook
RUN pip install awscli
RUN pip install mariasql
RUN pip install PyMySQL
RUN pip install boto3
RUN pip install pytz
RUN pip install redis
RUN pip install qrcode
RUN pip install Pillow
RUN pip install flask
